services:
  mysql:
    image: mysql:latest
    container_name: mysql_cdr
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: CDR-DB-MYSQL
    ports:
      - "3310:3306"
    volumes:
      - ./CDR-DB-MYSQL.sql:/docker-entrypoint-initdb.d/CDR-DB-MYSQL.sql
    networks:
      - CDR-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_cdr
    restart: always
    depends_on:
      - mysql
    ports:
      - "100:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      UPLOAD_LIMIT: 500M
    networks:
      - CDR-network

networks:
  CDR-network:
    name: CDR
    driver: bridge
